# ESLint config
# http://eslint.org/docs/user-guide/configuring
# https://jstools.dev/eslint-config/

root: true
extends: "@jsdevtools"

env:
  node: true

rules:
  '@typescript-eslint/ban-ts-comment': 'off'
