# Mocha options
# https://mochajs.org/#configuring-mocha-nodejs
# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml

spec:
  - test/fixtures/setup-mocks.js
  - test/fixtures/mocha-hooks.js
  - test/specs/**/*.spec.js

bail: false
timeout: 10000
slow: 2000
retries: 2
recursive: true
