# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

sudo: false
language: node_js
matrix:
  include:
    - node_js: 0.10
    - node_js: 0.11
    - node_js: 0.12
    - node_js: 4
    - node_js: 5
    - node_js: 6
      env: DEPLOY=true

# Mocha sometimes fails (not sure why), so when that happens, try again.
# If it fails a second time, then the CI build fails.
script: npm test || npm test
